INSERT INTO marcas ( nombre)  VALUES ('Epson'),('HP (Hewlett-Packard)'),('Canon'), ('Brother'),('Samsung'),('Xerox'),('Lexmark'),('Dell'),('Ricoh'),('Kyocera'),('Panasonic');

INSERT INTO roles (descripcion) VALUES ('ADMINSITRADOR'),('COMPUTO'),('JEFE DE AREA'),('PERSONAL');


INSERT INTO servicios (nombre) VALUES ('ADMINISTRADOR'),('COMPUTOS'),('CONTABLE'),('NEUROLOGIA Y NEUROCIRUGIA'),('DEPOSITO'),('QUIROFANO CENTRAL'),('GUARDIA CENTRAL'),('FACTURACION'),('NUTRICION'),('LABORATORIO CENTRAL'),('TELEMEDICINA'),('ESTADISTICA'),('CIRUGIA GENERAL'),('KINESIOLOGIA Y FISIOTERAPIA'),('ANATOMIA PATOLOGICA'),('TECNICA Y OPERATIVA'),('DIRECCION ADMINISTRATIVA'),('LIQUIDACION DE HABERES'),('DIRECCION MEDICA'),('JEFA DE DPTO DE ENFERMERIA'),('FARMACIA Y ESTERILIZACION'),('SERVICIO SOCIAL');

INSERT INTO tipo_carga (descripcion) VALUES ('ORIGINAL'),('RECARGA'),('ALTERNATIVO');

INSERT INTO tipo_cartuchos (descripcion) VALUES ('ESTANDAR'),('TONER'),('TINTA');

INSERT INTO colores (nombre) VALUES ('NEGRO (BLACK)'),('COLOR(C,M,Y)'),('CIAN (CYAN)'),('MAGENTA'),('AMARILLO (YELLOW)');

INSERT INTO tipo_impresoras (descripcion) VALUES ('INYECCION DE TINTA'),('LASER'),('MULTIFUNCION'),('TONER');

INSERT INTO estados (descripcion) VALUES ('SOLICITADA'),('APROBADA'),('OBSERVADA'),('REHACER');


